language: swift
os: osx
osx_image: xcode13.2
branches:
  only:
   - master

before_install:
  - gem install fastlane --no-ri --no-rdoc --no-document
install: true
script:
  - fastlane scan --scheme TAU --device "iPhone 13 Pro Max"

