language: swift
os: osx
osx_image: xcode13.2
branches:
  only:
   - master

before_install:
  - gem install fastlane
install: true
script:
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  - fastlane scan --scheme TAU --device "iPhone 13 Pro Max"

