language: swift
os: osx
osx_image: xcode13.2
branches:
  only:
   - master

before_install:
  - brew install fastlane
install: true
script:
  - fastlane scan --scheme TAU --device "iPhone 13 Pro Max"

